{"id":"node_modules/axios/lib/cancel/CanceledError.js","dependencies":[{"name":"G:\\3rd 1st  sem\\SE3040 Application Frameworks\\Assignment\\code\\ApplicationFramework-1\\frontend\\package.json","includedInParent":true,"mtime":1653452439450},{"name":"G:\\3rd 1st  sem\\SE3040 Application Frameworks\\Assignment\\code\\ApplicationFramework-1\\frontend\\node_modules\\axios\\package.json","includedInParent":true,"mtime":1653452366121},{"name":"../core/AxiosError","loc":{"line":3,"column":25,"index":42},"parent":"G:\\3rd 1st  sem\\SE3040 Application Frameworks\\Assignment\\code\\ApplicationFramework-1\\frontend\\node_modules\\axios\\lib\\cancel\\CanceledError.js","resolved":"G:\\3rd 1st  sem\\SE3040 Application Frameworks\\Assignment\\code\\ApplicationFramework-1\\frontend\\node_modules\\axios\\lib\\core\\AxiosError.js"},{"name":"../utils","loc":{"line":4,"column":20,"index":86},"parent":"G:\\3rd 1st  sem\\SE3040 Application Frameworks\\Assignment\\code\\ApplicationFramework-1\\frontend\\node_modules\\axios\\lib\\cancel\\CanceledError.js","resolved":"G:\\3rd 1st  sem\\SE3040 Application Frameworks\\Assignment\\code\\ApplicationFramework-1\\frontend\\node_modules\\axios\\lib\\utils.js"}],"generated":{"js":"'use strict';\r\n\r\nvar AxiosError = require('../core/AxiosError');\r\nvar utils = require('../utils');\r\n\r\n/**\r\n * A `CanceledError` is an object that is thrown when an operation is canceled.\r\n *\r\n * @class\r\n * @param {string=} message The message.\r\n */\r\nfunction CanceledError(message) {\r\n  // eslint-disable-next-line no-eq-null,eqeqeq\r\n  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED);\r\n  this.name = 'CanceledError';\r\n}\r\n\r\nutils.inherits(CanceledError, AxiosError, {\r\n  __CANCEL__: true\r\n});\r\n\r\nmodule.exports = CanceledError;\r\n"},"sourceMaps":{"js":{"mappings":[{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":1,"column":0},"generated":{"line":1,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":2,"column":0},"generated":{"line":2,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":3,"column":0},"generated":{"line":3,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":4,"column":0},"generated":{"line":4,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":5,"column":0},"generated":{"line":5,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":6,"column":0},"generated":{"line":6,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":7,"column":0},"generated":{"line":7,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":8,"column":0},"generated":{"line":8,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":9,"column":0},"generated":{"line":9,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":10,"column":0},"generated":{"line":10,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":11,"column":0},"generated":{"line":11,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":12,"column":0},"generated":{"line":12,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":13,"column":0},"generated":{"line":13,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":14,"column":0},"generated":{"line":14,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":15,"column":0},"generated":{"line":15,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":16,"column":0},"generated":{"line":16,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":17,"column":0},"generated":{"line":17,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":18,"column":0},"generated":{"line":18,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":19,"column":0},"generated":{"line":19,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":20,"column":0},"generated":{"line":20,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":21,"column":0},"generated":{"line":21,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":22,"column":0},"generated":{"line":22,"column":0}},{"source":"node_modules/axios/lib/cancel/CanceledError.js","original":{"line":23,"column":0},"generated":{"line":23,"column":0}}],"sources":{"node_modules/axios/lib/cancel/CanceledError.js":"'use strict';\r\n\r\nvar AxiosError = require('../core/AxiosError');\r\nvar utils = require('../utils');\r\n\r\n/**\r\n * A `CanceledError` is an object that is thrown when an operation is canceled.\r\n *\r\n * @class\r\n * @param {string=} message The message.\r\n */\r\nfunction CanceledError(message) {\r\n  // eslint-disable-next-line no-eq-null,eqeqeq\r\n  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED);\r\n  this.name = 'CanceledError';\r\n}\r\n\r\nutils.inherits(CanceledError, AxiosError, {\r\n  __CANCEL__: true\r\n});\r\n\r\nmodule.exports = CanceledError;\r\n"},"lineCount":23}},"error":null,"hash":"acbe0de906ee1499dbcf26d2ad185969","cacheData":{"env":{}}}